### ISSUE TITLE
Please make the functions from NaclUtil public

### ISSUE THREAD

**Issue by ppamorim** [bitmark-inc/tweetnacl-swiftwrap#8]
Hi. I am using this project in my cocoapods library and I need to use some functions from NaclUtil that are private. Could you please make `struct NaclUtil` public? Otherwise I will need to manually reimplement them in my source code.

**Comment by anhnguyenbitmark** [comment]
Which functions do you need to expose from `NaclUtil`? It was initially served for other methods, so I didn't make it public.

**Comment by ppamorim** [comment]
Mostly this function: https://github.com/ppamorim/skynet-swift/blob/master/Sources/Skynet/Model/SkynetUser.swift#L202

**Comment by danielrbrowne** [comment]
I'd also like to see this change, please. A note, however is that a small change to its implementation means that the library can be used on Linux where Apple's Security.framework isn't available. Currently I reimplemented the method as:

```swift
/// Generates cryptographically secure random data.
/// - Parameter count: The number of random bytes to return.
/// - Throws: An `CryptoError` if the random data could not be generated for some reason,
///           or if zero random bytes were requested.
/// - Returns: The requested number of cryptographically secure random bytes, as `Data`.
static func secureRandomData(count: Int) throws -> Data {

    // Generation method is platform dependent
    // (The Security framework is only available on Apple platforms).
    #if os(Linux)

    var bytes = [UInt8]()
    for _ in 0..<count {
        let randomByte = UInt8.random(in: UInt8.min...UInt8.max)
        bytes.append(randomByte)
    }
    let randomData = Data(bytes: &bytes, count: count)

    return randomData

    #else

    var randomData = Data(count: count)
    let result = try randomData.withUnsafeMutableBytes { bufferPointer -> Int32 in
        guard let baseAddress = bufferPointer.baseAddress else {
            throw Error.zeroRandomBytesRequested
        }

        return SecRandomCopyBytes(kSecRandomDefault, count, baseAddress)
    }

    guard result == errSecSuccess else {
        throw Error.randomBytesGenerationError(statusCode: result)
    }

    return randomData

    #endif
}
```

Also, another note whilst this is under discussion, specifying types as `public` has no effect if they are inside `internal`, `private` or `fileprivate` types. So for example: https://github.com/bitmark-inc/tweetnacl-swiftwrap/blob/master/Sources/TweetNacl/TweetNacl.swift#L14 is not exposed publicly because `NaclUtil` is `internal` (the default access level if no keyword is provided).

@anhnguyenbitmark Would you like me to open a PR with the above changes, or is this something that is in progress?

**Comment by ppamorim** [comment]
@anhnguyenbitmark The need came from the Dart library that has these functions exposed.

**Comment by alfrch** [comment]
Hi @anhnguyenbitmark i tried installing this library using version 1.0.2 through cocoapod but it seems that NaclUtil still not public

<img width="1237" alt="Screen Shot 2021-10-28 at 18 28 55" src="https://user-images.githubusercontent.com/41340469/139290224-ca000f33-fd37-4501-9bd8-1381b4dfd2fe.png">

![Screen Shot 2021-10-28 at 22 46 12](https://user-images.githubusercontent.com/41340469/139290666-c4168eda-e51c-44e2-ac79-104c1e1a6858.png)

![Screen Shot 2021-10-28 at 22 46 22](https://user-images.githubusercontent.com/41340469/139290682-955fd20b-5310-4ac0-bc78-c7efa59a3b1d.png)
